travis:
  secure:
    BINSTAR_TOKEN: I7EqXecVsPw1K9zTlwVGSKM+2kY/ZmihhWRALTiQRlpI3v90q1E8Jwbk77RspGUFk3qLzzKszLprImvv7a2YRP/CM8hix1VElPxG5Aqh+J3V1yOFTVu67Q/QHxaSZV1F9XbUb2LKQ35hIuZsKby00ttVeouHvjmxXNq0Aofi9hZKqODemgBT3v89ZRF4ixJYK8SFWE8D8jWpFUzauLsDehkxxV3XgyFLcP8fObI98YoQhGuw1xml9wiJPKDMkGsCg+UYEoL+aEuxjLlIZjlPkWfHXCK02+YYCfM4MbEjo9YUIWun6KrCriyykLHRlAf7soTjlStP+B/qElGBYs/BFRDPYsb9ixqyqSlZRc189yXisqygC0NHh0BNQKzVtxb9ph1fbVdry+U3oQTTA300mv8ptVa1UyXPk7IVEzPiJLplSWOnV0fch4mpl7rtdyuFmVp0ltf5CHJ+hoyiJGbCOc202cJXXurwyR7bUGZNhnhUBXlqpM91JYRJ1n9hwrp2Zy8HQ43evi81IQnGHjf+YUFB7EKoKBmr6o5SHm3qyXubmsphodvn8F9/eaeFiWsiemV7Z1Xc3GB0Fftx/yoN/n6h36YVJgXTIXScTvlF5ZQVpLsfYFjL0b0wEdG0nKiTOATcmTtsISpKXxzY5pvem0yLtD58gKkIAHvF4nBpIrU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
